# Generated by Django 5.2.14 on 2026-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desccription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
