# Generated by Django 5.2.14 on 2026-05-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_desccription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desccription',
            new_name='description',
        ),
    ]
