# Generated by Django 5.2.14 on 2026-05-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_state_lga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.state')),
            ],
        ),
    ]
