# Generated by Django 5.2.14 on 2026-05-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_variation'),
        ('store', '0009_alter_product_category_alter_product_modified_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
