# Generated by Django 5.2.14 on 2026-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0009_alter_product_category_alter_product_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variantion',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
