# Generated by Django 5.2.14 on 2026-05-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_variantion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variantion',
            new_name='variation',
        ),
    ]
